# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruxster}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher Petersen"]
  s.date = %q{2011-01-13}
  s.description = %q{An Object Graph Mapper (OGM) for mapping Ruby Objects onto graphs in a instance or Rexster, like CouchRest is for CouchDB}
  s.email = %q{christopher.petersen@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.textile",
    "Rakefile",
    "VERSION",
    "lib/ruxster.rb",
    "lib/ruxster/base.rb",
    "lib/ruxster/edge.rb",
    "lib/ruxster/vertex.rb",
    "ruxster.gemspec",
    "spec/base_spec.rb",
    "spec/edge_spec.rb",
    "spec/ruxster_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/vertex_spec.rb"
  ]
  s.homepage = %q{http://github.com/cpetersen/ruxster}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{An Object Graph Mapper (OGM) for Rexster}
  s.test_files = [
    "spec/base_spec.rb",
    "spec/edge_spec.rb",
    "spec/ruxster_spec.rb",
    "spec/spec_helper.rb",
    "spec/vertex_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, ["~> 1.2.4"])
      s.add_runtime_dependency(%q<excon>, ["~> 0.3.6"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["> 1.2.3"])
      s.add_runtime_dependency(%q<excon>, ["= 0.3.6"])
      s.add_runtime_dependency(%q<json>, ["= 1.2.4"])
    else
      s.add_dependency(%q<json>, ["~> 1.2.4"])
      s.add_dependency(%q<excon>, ["~> 0.3.6"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, ["> 1.2.3"])
      s.add_dependency(%q<excon>, ["= 0.3.6"])
      s.add_dependency(%q<json>, ["= 1.2.4"])
    end
  else
    s.add_dependency(%q<json>, ["~> 1.2.4"])
    s.add_dependency(%q<excon>, ["~> 0.3.6"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, ["> 1.2.3"])
    s.add_dependency(%q<excon>, ["= 0.3.6"])
    s.add_dependency(%q<json>, ["= 1.2.4"])
  end
end

